var data = [
	{ name: 'Ai Uehara', kname: '우에하라 아이', birth: 1992, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Aika', kname: '아이카', birth: 1990, cup: 'F', body: '슬랜더', style: '갸루' },
	{ name: 'Aika Yamagishi', kname: '야마기시 아이카', birth: 1992, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Airi Suzumura', kname: '스즈무라 아이리', birth: 1993, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Akiho Yoshizawa', kname: '요시자와 아키호', birth: 1984, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Ameri Hoshi', kname: '호시 아메리', birth: 1991, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'An Tsujimoto', kname: '츠지모토 안', birth: 1993, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Aoi Matsushima', kname: '마츠시마 아오이', birth: 1983, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Megumi Shino', kname: '시노 메구미', birth: 1990, cup: 'A', body: '로리', style: '청순' },
	{ name: 'Arisa Fujii', kname: '후지이 아리사', birth: 1996, cup: 'G', body: '슬랜더', style: '청순' },
	{ name: 'Arisu Mizusawa', kname: '미즈사와 아리스', birth: 1987, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Ayaka Tomoda', kname: '토모다 아야카', birth: 1988, cup: 'E', body: '슬랜더', style: '갸루' },
	{ name: 'Ayane Suzukawa', kname: '스즈카와 아야네', birth: 1993, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Azusa Nagasawa', kname: '나가사와 아즈사', birth: 1988, cup: 'I', body: '육덕', style: '섹시' },
	{ name: 'China Matsuoka', kname: '', birth: 1994, cup: 'H', body: '슬랜더', style: '청순' },
	{ name: 'Chinami Sakura', kname: '', birth: 1991, cup: 'G', body: '육덕', style: '갸루' },
	{ name: 'Eimi Fukada', kname: '', birth: 1998, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Ema Futaba', kname: '', birth: 1998, cup: 'F', body: '슬랜더', style: '청순' },
	{ name: 'Erika', name2: 'Moka', kname: '', birth: 1988, cup: 'G', body: '육덕', style: '갸루' },
	{ name: 'Erika Momotani', kname: '', birth: 1994, cup: 'C', body: '슬랜더', style: '섹시' },
	{ name: 'Haruka Itoh', kname: '', birth: 1986, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Haruna Kase', kname: '', birth: 1996, cup: 'I', body: '육덕', style: '청순' },
	{ name: 'Haruna Kawakita', kname: '', birth: 1996, cup: 'F', body: '슬랜더', style: '섹시' },
	{ name: 'Hibiki Natsume', kname: '', birth: 1998, cup: 'F', body: '슬랜더', style: '청순' },
	{ name: 'Hikari Sakuraba', kname: '', birth: 1998, cup: 'G', body: '육덕', style: '갸루' },
	{ name: 'Himari Hanazawa', kname: '', birth: 1998, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Hitomi Inoue', kname: '', birth: 1992, cup: 'I', body: '육덕', style: '청순' },
	{ name: 'Iyona Fujii', kname: '', birth: 1998, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Kaho Imai', kname: '', birth: 1999, cup: 'G', body: '슬랜더', style: '갸루' },
	{ name: 'Kana Momonogi', kname: '', birth: 1996, cup: 'F', body: '슬랜더', style: '청순' },
	{ name: 'Kana Yume', kname: '', birth: 1993, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Kanon Ichikawa', kname: '', birth: 2001, cup: 'A', body: '로리', style: '청순' },
	{ name: 'Kanon Takigawa', kname: '', birth: 1991, cup: 'D', body: '슬랜더', style: '섹시' },
	{ name: 'Karen Kaede', kname: '', birth: 1999, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Kirara Asuka', kname: '', birth: 1988, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Kokona Yuzuki', kname: '', birth: 1995, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Rio Fujisaki', name2: 'Kokone Mizutani', kname: '', birth: 1988, cup: 'E', body: '슬랜더', style: '갸루' },
	{ name: 'Kotori Ayase', kname: '', birth: 1996, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Makoto Yuuki', kname: '', birth: 1990, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Mana Hayashi', kname: '', birth: 2001, cup: 'A', body: '로리', style: '청순' },
	{ name: 'Mana Sakura', kname: '', birth: 1993, cup: 'F', body: '슬랜더', style: '청순' },
	{ name: 'Mao Hamasaki', kname: '', birth: 1993, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Masami Ichikawa', kname: '', birth: 1991, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Megu Kamijo', name2: 'Mei Miura', kname: '', birth: 1989, cup: 'G', body: '슬랜더', style: '섹시' },
	{ name: 'Meguri', name2: 'Megu Fujiura', kname: '', birth: 1989, cup: 'G', body: '육덕', style: '섹시' },
	{ name: 'Mei Matsumoto', kname: '', birth: 1993, cup: 'G', body: '육덕', style: '갸루' },
	{ name: 'Mei Satsuki', kname: '', birth: 2000, cup: 'G', body: '슬랜더', style: '청순' },
	{ name: 'Miharu Usa', kname: '', birth: 1992, cup: 'F', body: '육덕', style: '청순' },
	{ name: 'Miho Maeshima', kname: '', birth: 1989, cup: 'E', body: '슬랜더', style: '갸루' },
	{ name: 'Mikako Abe', kname: '', birth: 1994, cup: 'A', body: '로리', style: '청순' },
	{ name: 'Mikoto Tsukasa', kname: '', birth: 1992, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Miku Abeno', kname: '', birth: 1993, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Mimi Aku', kname: '', birth: 1993, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Mitsuki Nagisa', kname: '', birth: 1999, cup: 'B', body: '슬랜더', style: '청순' },
	{ name: 'Miyu Hoshino', kname: '', birth: 1987, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Miyuki Yokoyama', kname: '', birth: 1989, cup: 'C', body: '슬랜더', style: '섹시' },
	{ name: 'Mizuho Uehara', kname: '', birth: 1991, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Momoka', kname: '', birth: 0, cup: 'F', body: '슬랜더', style: '갸루' },
	{ name: 'Nana Ogura', kname: '', birth: 1990, cup: 'F', body: '슬랜더', style: '청순' },
	{ name: 'Nana Yaotome', kname: '', birth: 2001, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Nanami Matsumoto', kname: '', birth: 1994, cup: 'I', body: '육덕', style: '청순' },
	{ name: 'Nao Jinguji', kname: '', birth: 1997, cup: 'D', body: '슬랜더', style: '섹시' },
	{ name: 'Naomi', kname: '', birth: 1996, cup: 'H', body: '슬랜더', style: '갸루' },
	{ name: 'Natsumi Shiraishi', kname: '', birth: 1990, cup: 'F', body: '슬랜더', style: '섹시' },
	{ name: 'Neiro Suzuka', kname: '', birth: 1988, cup: 'J', body: '육덕', style: '갸루' },
	{ name: 'Rei Mizuna', kname: '', birth: 1987, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Remu Suzumori', kname: '', birth: 1997, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Rika Tsubaki', kname: '', birth: 1999, cup: 'G', body: '슬랜더', style: '청순' },
	{ name: 'Rina Yuki', kname: '', birth: 1985, cup: 'D', body: '슬랜더', style: '섹시' },
	{ name: 'Rio', name2: 'Tina Yuzuki', kname: '', birth: 1986, cup: 'C', body: '슬랜더', style: '섹시' },
	{ name: 'Rion', name2: 'Rara Anzai', name3: 'Shion Utsunomiya', kname: '', birth: 1994, cup: 'J', body: '슬랜더', style: '섹시' },
	{ name: 'Risa Kasumi', kname: '', birth: 1984, cup: 'G', body: '슬랜더', style: '섹시' },
	{ name: 'Risa Tsukino', kname: '', birth: 1989, cup: 'C', body: '슬랜더', style: '섹시' },
	{ name: 'Ruka Inaba', kname: '', birth: 2000, cup: 'H', body: '육덕', style: '청순' },
	{ name: 'Saeko Hiiragi', kname: '', birth: 1999, cup: 'G', body: '육덕', style: '청순' },
	{ name: 'Saika Kawakita', kname: '', birth: 1999, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Saki Mishima', kname: '', birth: 1992, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Sakura Sakurada', kname: '', birth: 1982, cup: 'E', body: '슬랜더', style: '갸루' },
	{ name: 'Sana Anju', name2: 'Kurumi Hina', kname: '', birth: 1989, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Saori Hara', kname: '', birth: 1988, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Sara Saizyo', kname: '', birth: 1989, cup: 'H', body: '슬랜더', style: '갸루' },
	{ name: 'Saya Niiyama', kname: '', birth: 1989, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Shino Kuraki', kname: '', birth: 1996, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Shion Yuumi', kname: '', birth: 1999, cup: 'I', body: '슬랜더', style: '청순' },
	{ name: 'Shiori Kamisaki', kname: '', birth: 1990, cup: 'G', body: '슬랜더', style: '섹시' },
	{ name: 'Shou Nishino', kname: '', birth: 1985, cup: 'C', body: '슬랜더', style: '섹시' },
	{ name: 'Shuri Atomi', kname: '', birth: 1995, cup: 'B', body: '슬랜더', style: '청순' },
	{ name: 'Shiori Yamate', kname: '', birth: 1994, cup: 'G', body: '슬랜더', style: '청순' },
	{ name: 'Sora Aoi', kname: '', birth: 1983, cup: 'F', body: '슬랜더', style: '섹시' },
	{ name: 'Tia', kname: '', birth: 1991, cup: 'H', body: '슬랜더', style: '섹시' },
	{ name: 'Tomoe Nakamura', kname: '', birth: 1990, cup: 'H', body: '육덕', style: '섹시' },
	{ name: 'Tsubasa Amami', kname: '', birth: 1988, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Tsubomi', kname: '', birth: 1987, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Tsukasa Aoi', kname: '', birth: 1990, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Ui Mita', kname: '', birth: 1990, cup: 'D', body: '슬랜더', style: '섹시' },
	{ name: 'Umi Hirose', kname: '', birth: 1995, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Yu Asakura', kname: '', birth: 1989, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Yu Namiki', kname: '', birth: 1989, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Yua Aida', kname: '', birth: 1984, cup: 'E', body: '슬랜더', style: '섹시' },
	{ name: 'Yua Sakuya', kname: '', birth: 1988, cup: 'F', body: '슬랜더', style: '섹시' },
	{ name: 'Yui Hatano', kname: '', birth: 1988, cup: 'D', body: '슬랜더', style: '섹시' },
	{ name: 'Yukari Maki', kname: '', birth: 1995, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Yuna Ogura', kname: '', birth: 1998, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Yuria Mano', kname: '', birth: 1993, cup: 'C', body: '슬랜더', style: '섹시' },
	{ name: 'Yuria Satomi', kname: '', birth: 1984, cup: 'D', body: '슬랜더', style: '섹시' },
	{ name: 'Yurina Momose', name2: 'Yua Kuramochi', kname: '', birth: 1990, cup: 'H', body: '슬랜더', style: '청순' },
	{ name: 'Yuzu Ogura', kname: '', birth: 1993, cup: 'F', body: '슬랜더', style: '섹시' },
	{ name: 'Airi Natsume', kname: '', birth: 1994, cup: 'C', body: '로리', style: '섹시' },
	{ name: 'Akari Mitani', kname: '', birth: 1997, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Anna Kami', kname: '', birth: 1996, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Arina Hashimoto', kname: '', birth: 1996, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Arisu Nanase', kname: '', birth: 1997, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Chiharu Miyazawa', kname: '', birth: 1996, cup: 'B', body: '슬랜더', style: '청순' },
	{ name: 'Chihiro Nishikawa', kname: '', birth: 1996, cup: 'B', body: '슬랜더', style: '청순' },
	{ name: 'Ema Yuina', kname: '', birth: 1994, cup: 'F', body: '슬랜더', style: '청순' },
	{ name: 'Hikaru Konno', kname: '', birth: 1994, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Ichika Kasagi', kname: '', birth: 1998, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Mia Nanasawa', kname: '', birth: 1998, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Miku Aoyama', kname: '', birth: 1993, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Minami Hatsukawa', kname: '', birth: 1995, cup: 'D', body: '슬랜더', style: '청순' },
	{ name: 'Momose Himari', kname: '', birth: 9999, cup: 'A', body: '슬랜더', style: '청순' },
	{ name: 'Nozomi Kitano', kname: '', birth: 1991, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Sari Kousaka', kname: '', birth: 1998, cup: 'H', body: '슬랜더', style: '청순' },
	{ name: 'Shoko Takahashi', kname: '', birth: 1993, cup: 'G', body: '슬랜더', style: '청순' },
	{ name: 'Sumire Mizukawa', name2: 'Emiri Momota', kname: '', birth: 1995, cup: 'D', body: '슬랜더', style: '섹시' },
	{ name: 'Suzu Harumiya', kname: '', birth: 1996, cup: 'F', body: '슬랜더', style: '청순' },
	{ name: 'Yui Shirasaka', kname: '', birth: 2000, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Konomi Nagisa', kname: '', birth: 1999, cup: 'H', body: '슬랜더', style: '청순' },
	{ name: 'Tina Nanami', kname: '', birth: 1993, cup: 'D', body: '슬랜더', style: '섹시' },
	{ name: 'Natsuki Rin', kname: '', birth: 1998, cup: 'E', body: '슬랜더', style: '청순' },
	{ name: 'Hana Shirato', kname: '', birth: 2000, cup: 'C', body: '슬랜더', style: '청순' },
	{ name: 'Hana Himesaki', kname: '', birth: 2000, cup: 'I', body: '육덕', style: '청순' },
	{ name: 'Kanon Ibuki', kname: '', birth: 2001, cup: 'G', body: '슬랜더', style: '청순' },
	{ name: 'Ru Yumemi', kname: '', birth: 1999, cup: 'I', body: '육덕', style: '섹시' },
	{ name: 'Sakura Miura', kname: '', birth: 1997, cup: 'G', body: '슬랜더', style: '청순' },
	{ name: 'Nozomi Ishihara', kname: '', birth: 2000, cup: 'G', body: '육덕', style: '섹시' },
	{ name: 'Tsubaki Sannomiya', kname: '', birth: 1998, cup: 'G', body: '슬랜더', style: '청순' },
	{ name: 'Kaoru Yasui', kname: '', birth: 1999, cup: 'H', body: '육덕', style: '청순' },
	{ name: 'Nozomi Mare', kname: '', birth: 1996, cup: 'F', body: '육덕', style: '섹시' },
	{ name: 'Yua Mikami', kname: '', birth: 1993, cup: 'F', body: '슬랜더', style: '청순' },
	{ name: 'Hitomi Shiraishi', kname: '', birth: 1971, cup: '', body: '슬랜더', style: '섹시' },
];

data.sort(function (a, b) {
	return a.name < b.name ? -1 : 1;
});
